name: Deploy Laravel API to AWS ECR + EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 🔹 Checkout the code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 🔹 Generate Unique Image Tag (Commit Hash + Timestamp)
      - name: Set Image Tag
        run: echo "IMAGE_TAG=$(git rev-parse --short HEAD)-$(date +%s)" >> $GITHUB_ENV

      # 🔹 Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 🔹 Log in to AWS ECR
      - name: Log in to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # 🔹 Build and Push Docker Image to AWS ECR
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/laravel-docker:${{ env.IMAGE_TAG }}

      # 🔹 Deploy to EC2 Instance (using SSH or SSM)
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # 🔹 Login to ECR on EC2
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ steps.login-ecr.outputs.registry }}

            # 🔹 Pull the latest image from ECR
            docker pull ${{ steps.login-ecr.outputs.registry }}/laravel-docker:${{ env.IMAGE_TAG }}

            # 🔹 Stop and Remove the Old Container (if exists)
            docker stop laravel-app || true
            docker rm laravel-app || true

            # 🔹 Run the New Docker Image
            docker run -d --name laravel-app -p 80:80 ${{ steps.login-ecr.outputs.registry }}/laravel-docker:${{ env.IMAGE_TAG }}
